Project do not build
ERROR MESSAGE================================
Running "less:production" (less) task
>> NameError: variable @link-hover-decoration is undefined in app/bower_components/bootstrap/less/scaffolding.less on line 55, column 22:
>> 54     color: @link-hover-color;
>> 55     text-decoration: @link-hover-decoration;
>> 56   }
Warning: Error compiling .tmp/styles/main.less Use --force to continue.

Aborted due to warnings.
==============================================

Proposed import in the bootstrap.less

I´m using node v4.2.3.
After corrected the project build normally.